[package]
name = "query_param_group"
version = "0.1.0"
authors = ["Robert <robert.balicki@gmail.com>"]
description = """
Query Param Groups for the Rocket framework
"""
license = "MIT/Apache-2.0"
repository = "https://github.com/rbalicki2/rocket-query-param-group"

[dependencies]
rocket = "0.2.6"